service: vu-amplify-lambda-personal-sql

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: true
  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

    
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  logRetentionInDays: 365
  environment:
    OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
    PERSONAL_SQL_DYNAMO_TABLE: ${self:service}-${sls:stage}-personal-sql
    PERSONAL_SQL_S3_BUCKET: ${self:service}-${sls:stage}-personal-sql
    ASSISTANTS_FILES_BUCKET_NAME: ${self:custom.stageVariables.ASSISTANTS_FILES_BUCKET_NAME}
    S3_FILE_TEXT_BUCKET_NAME: ${self:custom.stageVariables.S3_FILE_TEXT_BUCKET_NAME}
    PERSONAL_SQL_METADATA_TABLE: ${self:service}-${sls:stage}-personal-sql-metadata
    CHAT_ENDPOINT: ${self:custom.stageVariables.CHAT_ENDPOINT}
    DEFAULT_SECRET_PARAMETER_PREFIX: "/pdb"
    DEFAULT_ACCOUNT: "default"
    DEFAULT_LLM_QUERY_MODEL: "gpt-4o"
    OBJECT_ACCESS_DYNAMODB_TABLE: vu-amplify-object-access-${sls:stage}-object-access
    DATASOURCE_REGISTRY_ENDPOINT: ${self:custom.stageVariables.DATASOURCE_REGISTRY_ENDPOINT}
    HASH_FILES_DYNAMO_TABLE: ${self:custom.stageVariables.HASH_FILES_DYNAMO_TABLE}
    API_BASE_URL: ${self:custom.stageVariables.API_BASE_URL}
    ACCOUNTS_DYNAMO_TABLE: vu-amplify-${sls:stage}-accounts
    API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-${sls:stage}-api-keys
    COST_CALCULATIONS_DYNAMO_TABLE: vu-amplify-${sls:stage}-cost-calculations
    LAMBDA_PERSONAL_SQL_IAM_POLICY_NAME: ${self:service}-${sls:stage}-lambda-personal-sql-iam-policy

    

  apiGateway:
    restApiId:
      ${self:custom.stageVariables.REST_API_ID}
    restApiRootResourceId:
      ${self:custom.stageVariables.REST_API_ROOT_RESOURCE_ID}

  iam:
    role:
      managedPolicies:
        - arn:aws:iam::${aws:accountId}:policy/${self:provider.environment.LAMBDA_PERSONAL_SQL_IAM_POLICY_NAME}


functions:

  pdb_sql_files_db_describe:
    handler: service/core.describe_db_schema
    timeout: 30
    events:
      - http:
          path: pdb/sql/files/schema
          method: post
          cors: true


  pdb_sql_db_describe:
    handler: service/core.describe_personal_db_schema
    timeout: 30
    events:
      - http:
          path: pdb/sql/schema
          method: post
          cors: true


  pdb_sql_get_user_dbs:
    handler: service/core.get_user_dbs
    timeout: 30
    events:
      - http:
          path: pdb/sql/list
          method: post
          cors: true

  pdb_sql_create_db:
    handler: service/core.create_db
    timeout: 30
    events:
      - http:
          path: pdb/sql/create
          method: post
          cors: true

  pdb_sql_register_db:
    handler: service/core.register_db
    timeout: 30
    events:
      - http:
          path: pdb/sql/register
          method: post
          cors: true

  pdb_sql_llm_query_db:
    handler: service/core.llm_query_db
    timeout: 90
    events:
      - http:
          path: pdb/sql/llmquery
          method: post
          cors: true

  pdb_sql_query_db:
    handler: service/core.query_personal_db
    timeout: 30
    events:
      - http:
          path: pdb/sql/query
          method: post
          cors: true

resources:
  Resources:
    LambdaPersonalSQLIAMPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ${self:provider.environment.LAMBDA_PERSONAL_SQL_IAM_POLICY_NAME}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.HASH_FILES_DYNAMO_TABLE}"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:DescribeTable
                - dynamodb:UpdateItem
                - dynamodb:Scan
              Resource:
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.COST_CALCULATIONS_DYNAMO_TABLE}"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.COST_CALCULATIONS_DYNAMO_TABLE}/*"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PERSONAL_SQL_DYNAMO_TABLE}"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PERSONAL_SQL_METADATA_TABLE}"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PERSONAL_SQL_METADATA_TABLE}/index/CreatorIndex"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.API_KEYS_DYNAMODB_TABLE}"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.ACCOUNTS_DYNAMO_TABLE}"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.API_KEYS_DYNAMODB_TABLE}/index/*"
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.ACCOUNTS_DYNAMO_TABLE}/index/*"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.OBJECT_ACCESS_DYNAMODB_TABLE}"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - "arn:aws:s3:::${self:provider.environment.PERSONAL_SQL_S3_BUCKET}"
                - "arn:aws:s3:::${self:provider.environment.PERSONAL_SQL_S3_BUCKET}/*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - "arn:aws:s3:::${self:provider.environment.PERSONAL_SQL_S3_BUCKET}/*"
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - "arn:aws:s3:::${self:provider.environment.ASSISTANTS_FILES_BUCKET_NAME}/*"
                - "arn:aws:s3:::${self:provider.environment.S3_FILE_TEXT_BUCKET_NAME}/*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:PutParameter
              Resource:
                - "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:provider.environment.DEFAULT_SECRET_PARAMETER_PREFIX}/*"                

    DBBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PERSONAL_SQL_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
              - AllowedOrigins: ['*']
                AllowedMethods: ['PUT', 'POST']
                AllowedHeaders: ['*']
                MaxAge: 3000

    DistributedLocksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PERSONAL_SQL_DYNAMO_TABLE}
        AttributeDefinitions:
          - AttributeName: ResourceId
            AttributeType: S
        KeySchema:
          - AttributeName: ResourceId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true
        
    PersonalSQLMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PERSONAL_SQL_METADATA_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: creator
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CreatorIndex
            KeySchema:
              - AttributeName: creator
                KeyType: HASH
              - AttributeName: name
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true