service: vu-amplify-lambda-personal-sql

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

    
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  environment:
    OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-data
    FILES_S3_BUCKET_NAME: ${self:service}-${sls:stage}-blob

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - s3:GetObject
            - s3:PutObject
            - s3:HeadObject
            - s3:ListBucket
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}"


functions:

  core_function:
    handler: service/core.sample
    events:
      - http:
          path: someservice/sample
          method: post
          cors: true

      

        
           