# serverless-compose.yml
services:
  vu-amplify-embedding:
    path: ./embedding
 
  sql-connector:
    path: ./sql-connector
  
  langchain-base:
    path: ./langchain-base

  langchain-sql:
    path: ./langchain-sql
