service: amplify-${self:custom.stageVars.DEP_NAME}-utilities
frameworkVersion: '3'
package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-deployment-bucket
custom:

  stageVars: ${file(../var/${self:provider.stage}-var.yml)} 

  pythonRequirements:
    dockerizePip: true
    layer: true

  stages:
    - dev
    - staging
    - prod

  prune:
    automatic: true
    includeLayers: true
    number: 5    

  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}

         

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    restApiId:
      Fn::ImportValue: !Sub "${sls:stage}-RestApiId"
    restApiRootResourceId:
      Fn::ImportValue: !Sub "${sls:stage}-RestApiRootResourceId"  
  environment:
    #from stageVars file
    OAUTH_AUDIENCE: ${self:custom.stageVars.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVars.OAUTH_ISSUER_BASE_URL}
    IDP_PREFIX: ${self:custom.stageVars.IDP_PREFIX}
    #OPENAI_API_KEY_ARN: ${self:custom.stageVars.OPENAI_API_KEY_ARN}
    LLM_ENDPOINTS_SECRETS_NAME_ARN: ${self:custom.stageVars.LLM_ENDPOINTS_SECRETS_NAME_ARN}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - ${self:provider.environment.LLM_ENDPOINTS_SECRETS_NAME_ARN}

functions:
  execute_rename:
    timeout: 600
    handler: rename_chats.execute_rename
    events:
      - http:
          path: /execute_rename
          method: post
          cors: true
    layers:
      - Ref: PythonRequirementsLambdaLayer

