service: example-service

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

    
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  logRetentionInDays: 365
  apiGateway:
    restApiId:
      ${self:custom.stageVariables.REST_API_ID}
    restApiRootResourceId:
      ${self:custom.stageVariables.REST_API_ROOT_RESOURCE_ID}

  environment:
    OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
    LAMBDA_PYTHON_BASE_IAM_POLICY_NAME: ${self:service}-${sls:stage}-lambda-python-base-iam-policy


  iam:
    role:
      managedPolicies:
        - arn:aws:iam::${aws:accountId}:policy/${self:provider.environment.LAMBDA_PYTHON_BASE_IAM_POLICY_NAME}


functions:

  example_core_function:
    handler: service/core.sample
    events:
      - http:
          path: someservice/sample
          method: post
          cors: true
resources:
  Resources:

    LambdaPythonBaseAMPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ${self:provider.environment.LAMBDA_PYTHON_BASE_IAM_POLICY_NAME}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - someActio:GetAction
              Resource:
                - "arn:aws:someResource:${aws:region}:*:someResourceName"
      

        
           