service: example-service

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

    
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  logRetentionInDays: 365 #Set the log retention to 365 days for 800-171 Compliance
  apiGateway:
    restApiId:
      ${self:custom.stageVariables.REST_API_ID}
    restApiRootResourceId:
      ${self:custom.stageVariables.REST_API_ROOT_RESOURCE_ID}

  environment:
    OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
    LAMBDA_PYTHON_BASE_IAM_POLICY_NAME: ${self:service}-${sls:stage}-lambda-python-base-iam-policy


  iam:
    role:
      managedPolicies: #attach the managed policy to the Lambda functions for 800-171 Compliance
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::${aws:accountId}:policy/${self:provider.environment.LAMBDA_PYTHON_BASE_IAM_POLICY_NAME}


functions:

  example_core_function:
    handler: service/core.sample
    events:
      - http:
          path: someservice/sample
          method: post
          cors: true
resources:
  Resources:
    # Set up a managed policy for the Lambda functions for 800-171 Compliance
    LambdaPythonBaseAMPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: ${self:provider.environment.LAMBDA_PYTHON_BASE_IAM_POLICY_NAME}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - someActio:GetAction
              Resource:
                - "arn:aws:someResource:${aws:region}:*:someResourceName"
``` SampleDynamo:
    Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
        PointInTimeRecoverySpecification: #Enable PITR for 800-171 compliance
          PointInTimeRecoveryEnabled: true
        SSESpecification: #Enable encryption at rest for 800-171 compliance
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

      

        
           