service: amplify-${self:custom.stageVariables.DEP_NAME}-lambda-optimizer

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: true
  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

    
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  logRetentionInDays: 365
  environment:
    OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
    CHAT_ENDPOINT: ${self:custom.stageVariables.CHAT_ENDPOINT}
    DEFAULT_ACCOUNT: "default"
    DEFAULT_LLM_QUERY_MODEL: "gpt-4o"
    OBJECT_ACCESS_API_ENDPOINT: https://${self:custom.stageVariables.CUSTOM_API_DOMAIN}/utilities/can_access_objects
    LAMBDA_OPTIMIZER_IAM_POLICY_NAME: amplify-${self:custom.stageVariables.DEP_NAME}-lambda-optimizer-${sls:stage}-iam-policy

  apiGateway:
    restApiId:
      Fn::ImportValue: !Sub "${sls:stage}-RestApiId"
    restApiRootResourceId:
      Fn::ImportValue: !Sub "${sls:stage}-RestApiRootResourceId"
  

  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole


functions:

  generate_optimized_prompt:
    handler: service/core.optimize
    timeout: 30
    events:
      - http:
          path: optimizer/prompt
          method: post
          cors: true


