service: amplify-${self:custom.stageVars.DEP_NAME}-amplify-js
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-prune-plugin 

custom:
  serverless-offline: 
    custom:
      config: ${file(../var/${self:provider.stage}-var.yml)} 
  stageVars: ${file(../var/${self:provider.stage}-var.yml)} 

  stages:
    - dev
    - staging
    - prod
    
  prune:
    automatic: true
    includeLayers: true
    number: 5    


provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  environment:
    #Local Resources Created
    TRACING_ENABLED: false
    TRACE_BUCKET_NAME: amplify-${self:custom.stageVars.DEP_NAME}-${sls:stage}-chat-traces

    #Reference Resource createb by other services
    FILES_DYNAMO_TABLE: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-user-files
    REQUEST_STATE_DYNAMO_TABLE: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-request-state
    HASH_FILES_DYNAMO_TABLE: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-hash-files
    CHAT_USAGE_DYNAMO_TABLE: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-chat-usage
    S3_CHUNKS_BUCKET_NAME: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-rag-chunks
    S3_FILE_TEXT_BUCKET_NAME: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-file-text
    DATASOURCES_QUERY_ENDPOINT: https://${self:custom.stageVars.CUSTOM_API_DOMAIN}/assistant/files/query
    USAGE_ENDPOINT: https://${self:custom.stageVars.CUSTOM_API_DOMAIN}/accounting/charge
    RAG_ENDPOINT: https://${self:custom.stageVars.CUSTOM_API_DOMAIN}/embedding-dual-retrieval
    OBJECT_ACCESS_PERMISSIONS_ENDPOINT: https://${self:custom.stageVars.CUSTOM_API_DOMAIN}/utilities/can_access_objects
    ASSISTANTS_DYNAMODB_TABLE: amplify-${self:custom.stageVars.DEP_NAME}-assistants-${sls:stage}-assistants
    ASSISTANTS_ALIASES_DYNAMODB_TABLE: amplify-${self:custom.stageVars.DEP_NAME}-assistants-${sls:stage}-assistant-aliases
    ASSISTANT_QUEUE_NAME: amplify-${self:custom.stageVars.DEP_NAME}-lanbda-${sls:stage}-assistant-tasks
    ASSISTANT_TASK_RESULTS_BUCKET_NAME: amplify-${self:custom.stageVars.DEP_NAME}-lambda-${sls:stage}-assistant-results
    #ASSISTANTS_AZURE_CODE_INTERPRETER_ENDPOINT: ${self:custom.stageVars.ASSISTANTS_AZURE_CODE_INTERPRETER_ENDPOINT}/chat_with_code_interpreter
    #ASSISTANTS_CREATE_CODE_INTERPRETER_ENDPOINT: ${self:custom.stageVars.ASSISTANTS_CREATE_CODE_INTERPRETER_ENDPOINT}/assistant/create
    #ASSISTANTS_OPENAI_CODE_INTERPRETER_ENDPOINT: ${self:custom.stageVars.ASSISTANTS_OPENAI_CODE_INTERPRETER_ENDPOINT}
    ASSISTANTS_OPENAI_CODE_INTERPRETER_ENDPOINT: ${param:ASSISTANTS_OPENAI_CODE_INTERPRETER_ENDPOINT}
    ASSISTANTS_AZURE_CODE_INTERPRETER_ENDPOINT: ${param:ASSISTANTS_AZURE_CODE_INTERPRETER_ENDPOINT}/chat_with_code_interpreter
    ASSISTANTS_CREATE_CODE_INTERPRETER_ENDPOINT: ${param:ASSISTANTS_CREATE_CODE_INTERPRETER_ENDPOINT}/assistant/create
    ASSISTANT_LOGS_BUCKET_NAME: amplify-${self:custom.stageVars.DEP_NAME}-${sls:stage}-assistant-chat-logs
   
    #Stand Alone Vars Referenced from local vars file
    #AZURE_OPENAI_RESOURCE_NAME: ${self:custom.stageVars.AZURE_OPENAI_RESOURCE_NAME}
    RAG_ASSISTANT_MODEL_ID: ${self:custom.stageVars.RAG_ASSISTANT_MODEL_ID}
    LLM_ENDPOINTS_SECRETS_NAME: ${self:custom.stageVars.LLM_ENDPOINTS_SECRETS_NAME}
    LLM_ENDPOINTS_SECRETS_NAME_ARN: ${self:custom.stageVars.LLM_ENDPOINTS_SECRETS_NAME_ARN}
    COGNITO_USER_POOL_ID: ${self:custom.stageVars.COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${self:custom.stageVars.COGNITO_CLIENT_ID}
    OAUTH_AUDIENCE: ${self:custom.stageVars.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVars.OAUTH_ISSUER_BASE_URL}
    #SECRETS_NAME: ${self:custom.stageVars.SECRETS_NAME}
    SECRETS_ARN_NAME: ${self:custom.stageVars.SECRETS_ARN_NAME}
    IDP_PREFIX: ${self:custom.stageVars.IDP_PREFIX}


    

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - s3:GetObject
            - s3:ListBucket
            - dynamodb:GetItem
            - dynamodb:PutItem
            - bedrock:InvokeModelWithResponseStream
            - bedrock:InvokeModel
          Resource:
            - "arn:aws:secretsmanager:us-east-1:*:secret:${self:provider.environment.SECRETS_ARN_NAME}"
            - "${self:provider.environment.LLM_ENDPOINTS_SECRETS_NAME_ARN}"
            - "arn:aws:s3:::${self:provider.environment.S3_FILE_TEXT_BUCKET_NAME}/*"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.CHAT_USAGE_DYNAMO_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.CHAT_USAGE_DYNAMO_TABLE}/*"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.REQUEST_STATE_DYNAMO_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.HASH_FILES_DYNAMO_TABLE}"
            - 'arn:aws:secretsmanager:us-east-1:*:secret:${self:provider.environment.SECRETS_ARN_NAME}'
            - "arn:aws:s3:::${self:provider.environment.ASSISTANT_TASK_RESULTS_BUCKET_NAME}/*"
            - "arn:aws:s3:::${self:provider.environment.ASSISTANT_LOGS_BUCKET_NAME}/*"
            - "arn:aws:sqs:${aws:region}:*:${self:provider.environment.ASSISTANT_QUEUE_NAME}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.REQUEST_STATE_DYNAMO_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.HASH_FILES_DYNAMO_TABLE}"
            - 'arn:aws:bedrock:*::foundation-model/anthropic.claude-instant-v1'
            - 'arn:aws:bedrock:*::foundation-model/anthropic.claude-v2:1'
            - 'arn:aws:bedrock:*::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0'
            - 'arn:aws:bedrock:*::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
            - 'arn:aws:bedrock:*::foundation-model/anthropic.claude-3-opus-20240229-v1:0'
            - 'arn:aws:bedrock:*::foundation-model/mistral.mistral-7b-instruct-v0:2'
            - 'arn:aws:bedrock:*::foundation-model/mistral.mixtral-8x7b-instruct-v0:1'
            - 'arn:aws:bedrock:*::foundation-model/mistral.mistral-large-2402-v1:0'

        - Effect: Allow
          Action:
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.REQUEST_STATE_DYNAMO_TABLE}"
        
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.ASSISTANTS_ALIASES_DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.ASSISTANTS_DYNAMODB_TABLE}"

functions:
  chat:
    handler: index.handler
    memorySize: 1024
    timeout: 900
    url:
      cors: true
      invokeMode: RESPONSE_STREAM

resources:
  Resources:
    RequestStateDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: requestId
            AttributeType: S
          -
            AttributeName: user
            AttributeType: S
        KeySchema:
          -
            AttributeName: user
            KeyType: HASH
          -
            AttributeName: requestId
            KeyType: RANGE
        TableName: ${self:provider.environment.REQUEST_STATE_DYNAMO_TABLE}