service: chat-billing

frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
  serverless-offline: 
    custom:
      config: ${file(../var/${self:provider.stage}-var.yml)}

  stageVariables: ${file(../var/${self:provider.stage}-var.yml)}
  stages:
    - dev
    - staging
    - prod

  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  deploymentBucket:
    name: ${self:service}-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256
  
  apiGateway:
    restApiId:
      ${self:custom.stageVariables.REST_API_ID}
    restApiRootResourceId:
      ${self:custom.stageVariables.REST_API_ROOT_RESOURCE_ID}
  
  environment:
    MODEL_EXCHANGE_RATE_TABLE: ${self:service}-${sls:stage}-model-exchange-rates
    ADDITIONAL_CHARGES_TABLE: ${self:service}-${sls:stage}-additional-charges
    HISTORY_USAGE_TABLE: ${self:service}-${sls:stage}-history-usage
    CHAT_USAGE_TABLE: vu-amplify-${sls:stage}-chat-usage

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
          Resource:
            - "arn:aws:secretsmanager:us-east-1:*:secret:aws/ses/credentials-i82Vzw"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ADDITIONAL_CHARGES_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ADDITIONAL_CHARGES_TABLE}/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.HISTORY_USAGE_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.HISTORY_USAGE_TABLE}/*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHAT_USAGE_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CHAT_USAGE_TABLE}/*"


functions:
  # sets the value of the model exchange rates
  # TODO:
  # - finish implementation of AWS pricing API once Amazon fixes pricing API bug
  # - make this trigger daily to keep rates up to date
  updateModelExchangeRateTable:
    handler: exchange_rates/update_table.updateModelExchangeRateTable
    memorySize: 128
    events:
      - http:
          path: billing/update-model-exchange-rates
          method: post
          cors: true
    environment:
      EXCHANGE_RATE_TABLE: ${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}

  
  # calculates cost of all usage from the chat usage table and the additional charges table
  # saves costs for each user, coa, and date to the history usage table
  # triggered at the start of each day and month
  trackUsage:
    handler: usage/track_usage.handler
    memorySize: 128
    events:
      - schedule:
          rate: cron(0 0 * * ? *) # trigger at midnight UTC every day
      - schedule:
          rate: cron(0 0 1 * ? *) # trigger at midnight UTC on the first day of every month
    environment:
      MODEL_EXCHANGE_RATE_TABLE: ${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}
      HISTORY_USAGE_TABLE: ${self:provider.environment.HISTORY_USAGE_TABLE}
      CHAT_USAGE_TABLE: ${self:provider.environment.CHAT_USAGE_TABLE}
      ADDITIONAL_CHARGES_TABLE: ${self:provider.environment.ADDITIONAL_CHARGES_TABLE}


  # TODO: add real time report generator
  #       add additional charges logic once that is ready
  # reportGenerator:
  #   handler: usage/report_generator.handler
  #   memorySize: 128
  #   events:
  #     - http:
  #         path: billing/report-generator
  #         method: post
  #         cors: true
  #   environment:
  #     MODEL_EXCHANGE_RATE_TABLE: ${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}
  #     HISTORY_USAGE_TABLE: ${self:provider.environment.HISTORY_USAGE_TABLE}
  #     CHAT_USAGE_TABLE: ${self:provider.environment.CHAT_USAGE_TABLE}
  #     ADDITIONAL_CHARGES_TABLE: ${self:provider.environment.ADDITIONAL_CHARGES_TABLE}

resources:
  Resources:
    # model rates needed for usage cost calculations
    ExchangeRateTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}
        AttributeDefinitions:
          - AttributeName: 'ModelID'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'ModelID'
            KeyType: 'HASH'

    # TODO: implement this table only containing code interpreter items
    #       tell karely to send code interpreter charges to this table
    # in the future this may contain charges for assistants, infrastructure/lambdas, RAG, Dynamo, S3
    AdditionalChargesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.ADDITIONAL_CHARGES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'

    # daily and monthly usage saved to this table
    HistoryUsageTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.HISTORY_USAGE_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'userDateComposite'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
          - AttributeName: 'userDateComposite'
            KeyType: 'RANGE'