service: chat-billing-service

frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
  serverless-offline: 
    custom:
      config: ${file(../var/${self:provider.stage}-var.yml)}

  stageVariables: ${file(../var/${self:provider.stage}-var.yml)}
  stages:
    - dev
    - staging
    - prod

  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}
  
  # uncomment this to enable a post-deployment automation that will trigger updating the table
  # custom:
  #   scripts:
  #     hooks:
  #       'after:deploy:deploy': serverless invoke --function updateModelExchangeRateTable --stage dev

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  deploymentBucket:
    name: ${self:service}-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256
  
  environment:
    MODEL_EXCHANGE_RATE_TABLE: ${self:custom.stageVariables.MODEL_EXCHANGE_RATE_TABLE}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
          
          Resource:
            - "arn:aws:secretsmanager:us-east-1:514391678313:secret:aws/ses/credentials-i82Vzw"
            - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}"


functions:
  updateModelExchangeRateTable:
    runtime: python3.11
    handler: exchange_rates/update_table.updateModelExchangeRateTable
    events:
      - http:
          path: billing/update-model-exchange-rates
          method: post
          cors: true
    environment:
      EXCHANGE_RATE_TABLE: ${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}

resources:
  Resources:
    ExchangeRateTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.MODEL_EXCHANGE_RATE_TABLE}
        AttributeDefinitions:
          - AttributeName: 'ModelID'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'ModelID'
            KeyType: 'HASH'