service: vu-amplify-object-access


frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

  serverless-offline: 
    custom:
      config: ${file(../var/${self:provider.stage}-var.yml)} 

  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  deploymentBucket:
    name: ${self:service}-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256

  apiGateway:
    restApiId:
      ${self:custom.stageVariables.REST_API_ID}
    restApiRootResourceId:
      ${self:custom.stageVariables.REST_API_ROOT_RESOURCE_ID}    
            
functions:

  cognito_users_get_emails:
    handler: cognito_users.get_emails
    layers:
      - Ref: PythonRequirementsLambdaLayer    
    timeout: 30
    events:
      - http:
          path: /utilities/emails
          method: get
    environment: 
      COGNITO_USERS_TABLE: ${self:service}-${sls:stage}-cognito-users
      OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
      OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
      COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      API_KEY_TABLE: ${self:service}-${sls:stage}-api-keys
      API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys
    
    iamRoleStatements:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem

            Resource:
              - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-cognito-users"
              - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-api-keys"

  get_cognito_amplify_groups:
    handler: cognito_users.get_user_groups
    layers:
      - Ref: PythonRequirementsLambdaLayer
    timeout: 30   
    events:
      - http:
          path: /utilities/get_user_groups
          method: get
    environment: 
      COGNITO_USERS_TABLE: ${self:service}-${sls:stage}-cognito-users
      OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
      OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
      COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys
    
    iamRoleStatements:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:GetItem

            Resource:
              - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-cognito-users"      

  share_src_ids:
    runtime: python3.10
    handler: .share_src_ids
    layers:
      - Ref: PythonRequirementsLambdaLayer

    timeout: 300
    events:
      - http:
          path: /utilities/object_access
          method: post
          cors: true
    environment:
      OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
      OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
      COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      OBJECT_ACCESS_DYNAMODB_TABLE: ${self:service}-${sls:stage}-object-access
      API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys

    iamRoleStatements:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem

            Resource:
              - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-object-access"

  update_ojbect_perms:
    runtime: python3.10
    handler: object_access.update_object_permissions
    layers:
      - Ref: PythonRequirementsLambdaLayer
    timeout: 300
    events:
      - http:
          path: /utilities/update_object_permissions
          method: post
          cors: true
    environment:
      OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
      OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
      COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      OBJECT_ACCESS_DYNAMODB_TABLE: ${self:service}-${sls:stage}-object-access
      API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys

    iamRoleStatements:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem

            Resource:
              - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-object-access"


  can_access_objects:
    runtime: python3.10
    handler: object_access.can_access_objects
    layers:
      - Ref: PythonRequirementsLambdaLayer
    timeout: 15
    events:
      - http:
          path: /utilities/can_access_objects
          method: post
          cors: true
    environment:
      OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
      OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
      COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      OBJECT_ACCESS_DYNAMODB_TABLE: ${self:service}-${sls:stage}-object-access
      API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys

    iamRoleStatements:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
            Resource:
              - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-object-access"

  simulate_access:
     runtime: python3.10
     handler: object_access.simulate_access_to_objects
     layers:
       - Ref: PythonRequirementsLambdaLayer
     timeout: 15
     events:
       - http:
           path: /utilities/simulate_access_to_objects
           method: post
           cors: true
     environment:
       OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
       OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
       COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
       OBJECT_ACCESS_DYNAMODB_TABLE: ${self:service}-${sls:stage}-object-access
       API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys

     iamRoleStatements:
           - Effect: Allow
             Action:
               - dynamodb:Query
               - dynamodb:Scan
               - dynamodb:GetItem
             Resource:
               - "arn:aws:dynamodb:${self:provider.region}:514391678313:table/${self:service}-${sls:stage}-object-access"


  create_cognito_group:
      runtime: python3.10
      handler: object_access.create_cognito_group
      layers:
        - Ref: PythonRequirementsLambdaLayer
  
      timeout: 300
      events:
        - http:
            path: /utilities/create_cognito_group
            method: post
            cors: true
      environment:
        OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
        OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
        COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
        API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys
  
      iamRoleStatements:
        - Effect: Allow
          Action:
            - cognito-idp:CreateGroup
            - cognito-idp:AdminAddUserToGroup
          Resource:
            - arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:custom.stageVariables.COGNITO_USER_POOL_ID}

  sync_cognito_users:
    runtime: python3.11
    handler: cognito_users_sync.sync_users_to_dynamo  # Update with the actual path to your handler
    timeout: 900  # Set an appropriate timeout, max is 15 minutes (900 seconds)
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - schedule:
          rate: rate(5 minutes)  # Example: run every hour
          enabled: true
    environment:
      COGNITO_USER_POOL_ID: ${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      COGNITO_USERS_DYNAMODB_TABLE: ${self:service}-${sls:stage}-cognito-users
      API_KEYS_DYNAMODB_TABLE: vu-amplify-object-access-dev-api-keys

    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource:
          - arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:custom.stageVariables.COGNITO_USER_POOL_ID}
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource:
          - !GetAtt CognitoUsersTable.Arn

resources:
  Conditions:
    IsProd:
      'Fn::Equals':
        - ${self:provider.stage}
        - 'prod'
  
  Resources:
    ObjectAccessTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-${sls:stage}-object-access
        AttributeDefinitions:
          - AttributeName: 'object_id'
            AttributeType: 'S'
          - AttributeName: 'principal_id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'object_id'
            KeyType: 'HASH'  # Partition key
          - AttributeName: 'principal_id'
            KeyType: 'RANGE'  # Sort key
        GlobalSecondaryIndexes:
          - IndexName: 'PrincipalIdIndex'
            KeySchema:
              - AttributeName: 'principal_id'
                KeyType: 'HASH'  # Partition key for the secondary index
            Projection:
              ProjectionType: 'ALL'
    
    CognitoUsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-${sls:stage}-cognito-users
        AttributeDefinitions:
          - AttributeName: 'user_id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'user_id'
            KeyType: 'HASH'   

    ApiKeyTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-${sls:stage}-api-keys
        AttributeDefinitions:
          - AttributeName: 'api_owner_id'
            AttributeType: 'S'
          - AttributeName: 'apiKey'
            AttributeType: 'S' 
        KeySchema:
          - AttributeName: 'api_owner_id'
            KeyType: 'HASH'
        GlobalSecondaryIndexes:
          - IndexName: ApiKeyIndex
            KeySchema:
              - AttributeName: apiKey
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'          
          
